#geka116(1.0)
# RX на RO а TX на DI і flow на de-re (при позетивному кконекті ритмічно мигає диод конекта наморді)
substitutions:
  plug_name: (geka116)
  ip_name: (geka116)
  wifi_ip: '192.168.3.116'
  jeka_tx_pin: GPIO17
  jeka_rx_pin: GPIO16
  flow_control_pin: GPIO23
esphome:
  project:
    name: "geka116"
    version: "1.0.0"
  name: geka116       
  platform: ESP32       
  board: nodemcu-32s    
  on_boot:
    priority: 800
    then:
## 
wifi:
  output_power: 20dB
  ssid: "--сід вафлі--"
  password: "пароль"
  fast_connect: on
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: 192.168.3.1
    subnet: 255.255.255.0
  ap:
    password: "пароль"
captive_portal:
##
logger:
  logs:
    climate: none
    sensor: none
    component: ERROR

##
api:
 reboot_timeout: 0s

##
ota:
  - platform: esphome
## 
web_server:
  port: 80
  local: true
# Иницыализацыя шины i2c без сканировки..
i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: false
    frequency: 100kHz
##============================================================================##
uart:
  - id: uart_jeka
    baud_rate: 115200
    rx_buffer_size: 384
    tx_pin: ${jeka_tx_pin}
    rx_pin: ${jeka_rx_pin}
modbus:
  - id: modbus_jeka
    uart_id: uart_jeka
    flow_control_pin: ${flow_control_pin}
    send_wait_time: 200ms
modbus_controller:
  - id: bms0
    address: 0x01
    modbus_id: modbus_jeka
    setup_priority: -10
    update_interval: 5s
    command_throttle: 50ms
##============================================================================##
time:
  - platform: homeassistant
    id: esptime
    timezone: UTC-2
interval:
# Частота переключения екрана
  - interval: 10s
    then:
      - display.page.show_next: oled_display
      - component.update: oled_display
### - - - - - - - - - - - - -   текстовий  - - - - - - - - - -  - - - ###
text_sensor:
  - platform: template
    name: "${ip_name} esptime"
    entity_category: diagnostic
    id: timeee
    lambda:
          char str[17];
          time_t currTime = id(esptime).now().timestamp;
          strftime(str, sizeof(str), "%d-%m-%Y %H:%M", localtime(&currTime));
          return  { str };

# 
  - platform: wifi_info
    ip_address:
      id: IP_Address
### - - - - - - - - - - - - -  бинарные сенсор  - - - - - - - - - - -  - - - ###
binary_sensor:
## статус подключения к ховму
  - platform: status
    id: conekt_API


### - - - - - - - - - - - - - - - - сенсоры - - - - - - - - - - - -  - - - - ###
sensor:
#Сумуємо за добу
  - platform: total_daily_energy
    name: "BatCurrentt_day"
    id: BatCurrentt_day
    power_id: BatCurrentt
    unit_of_measurement: 'kWh'
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  # 0x1200    0    UINT16    2    R    CellVol0    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 1"
    address: 0x1200
    register_type: holding
    value_type: U_WORD
    register_count: 32  # read up to CellVol31
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  # 0x1202    2    UINT16    2    R    CellVol1    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 2"
    address: 0x1202
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1204    4    UINT16    2    R    CellVol2    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 3"
    address: 0x1204
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1206    6    UINT16    2    R    CellVol3    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 4"
    address: 0x1206
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1208    8    UINT16    2    R    CellVol4    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 5"
    address: 0x1208
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x120A   10    UINT16    2    R    CellVol5    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 6"
    address: 0x120A
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x120C   12    UINT16    2    R    CellVol6    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 7"
    address: 0x120C
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x120E   14    UINT16    2    R    CellVol7    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 8"
    address: 0x120E
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1210   16    UINT16    2    R    CellVol8    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 9"
    address: 0x1210
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1212   18    UINT16    2    R    CellVol9    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 10"
    address: 0x1212
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1214   20    UINT16    2    R    CellVol10   mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 11"
    address: 0x1214
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1216   22    UINT16    2    R    CellVol11   mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 12"
    address: 0x1216
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

# 0x1218   24    UINT16    2    R    CellVol12   mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 13"
    address: 0x1218
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x121A   26    UINT16    2    R    CellVol13   mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 14"
    address: 0x121A
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x121C   28    UINT16    2    R    CellVol14   mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 15"
    address: 0x121C
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x121E   30    UINT16    2    R    CellVol15   mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "cell voltage 16"
    address: 0x121E
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1244   68    UINT16    2    R    CellVolAverage    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "CellVolAverage"
    id: VolAverage
    address: 0x1244
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # 0x1246   70    UINT16    2    R    CellVoltageDifferenceMax    mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "CellVoltageDifference"
    id: VoltageDiff
    address: 0x1246
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  # 0x1248   72    UINT8/UINT8 2  R    MaxVolCellNbr / MinVolCellNbr
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "max voltage cell number"
    id: max_voltage_cell
    address: 0x1248
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: ""
    state_class: measurement
    accuracy_decimals: 0
    bitmask: 0xFF00
    filters:
      - offset: 1.0

  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "min voltage cell number"
    id: min_voltage_cell
    address: 0x1248
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: ""
    state_class: measurement
    accuracy_decimals: 0
    bitmask: 0x00FF
    filters:
      - offset: 1.0

  # 0x128A   138    INT16    2    R    TempMos         0.1 °C
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "mosfet temperature"
    id: mosfet_temp
    address: 0x128A
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.1
# 0x129C   156    INT16    2    R    TempBat 1       0.1 °C
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "TempBat 1"
    id: TempBat_1
    address: 0x129C
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.1
# 0x129E   158    INT16    2    R    TempBat 2       0.1 °C
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "TempBat 2"
    id: TempBat_2
    address: 0x129E
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.1
  # 0x1290   144   UINT32    4    R    BatVol          mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "total voltage"
    id: total_voltage
    address: 0x1290
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.001
# 0x1294   148   UINT32    4    R    BatWatt         mW
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "BatCurrentt"
    id: BatCurrentt
    address: 0x1294
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "W"
    state_class: measurement
    filters:
      - multiply: 0.001
# 0x12A8   168    INT32    2    R    SOCCapRemain    mAH
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "SOCCapRemainn"
    id: SOCCapRemainn
    address: 0x12A8
    register_type: holding
    value_type: U_DWORD
    unit_of_measurement: "Ah"
    state_class: measurement
    filters:
      - multiply: 0.001
# 0x12A6   166 UINT8+UINT8 2    R    BalanStatatus (2:放电; 1:充电 ; 0:关闭) / SOCStateOfcharge %
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "SOCStateOfcharge"
    id: SOCStateOfcharge
    address: 0x12A6
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 0
    bitmask: 0x00FF

# 0x12A6   166 UINT8+UINT8 2    R    BalanStatatus (2:放电; 1:充电 ; 0:关闭) / SOCStateOfcharge %
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "BalanStatatus"
    address: 0x12A6
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: ""
    state_class: measurement
    accuracy_decimals: 0
    bitmask: 0xFF00

  # 0x12C0   192 UINT8+UINT8 Charge (1:打开 ; 0:关闭) / Discharge (1:打开 ; 0:关闭)
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "Charge"
    address: 0x12C0
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: ""
    state_class: measurement
    accuracy_decimals: 0
    bitmask: 0x00FF

  # 0x12C0   192 UINT8+UINT8 Charge (1:打开 ; 0:关闭) / Discharge (1:打开 ; 0:关闭)
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "Discharge"
    address: 0x12C0
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: ""
    state_class: measurement
    accuracy_decimals: 0
    bitmask: 0xFF00

# уровень вайфай сигнала
  - platform: wifi_signal
    name: "${ip_name} WiFi signal:"  
    entity_category: diagnostic
    id: wifi_sig
    update_interval: 60s
    filters:
      - lambda: return x + 100.0;
    unit_of_measurement: "%"
##------------------------------OLED1306--------------------------------------##
# Робота с шрифтами
font:
  - file: "fonts/Montserrat-Bold.ttf"
    id: font_small
    size: 15
  - file: "fonts/Montserrat-Bold.ttf"
    id: font_medium
    size: 18
  - file: "fonts/Montserrat-Bold.ttf"
    id: font_large
    size: 33

## робота с картинками (фон белий обизательно)
image:
  - file: "images/Wh.png"
    id: "Wh" 
    resize: 30x30
  - file: "images/compresor.png"
    id: "compresor" 
    resize: 25x25

## Окно-анимация-делаем три соя-добавляем три кадра-стоя на кадре-вибираем слой(контрол-альт-шифт-s)
animation:
  - file: "images/HAapi_ani.gif"
    id: HAapi_ani
    resize: 18x18

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    i2c_id: bus_a
    address: 0x3C
    id: oled_display
    pages:
      - id: page_1
        lambda: |-
          //основная постояная
          it.printf(20, 0, id(font_small), "SOC_116");
          it.printf(20, 10 , id(font_large), "%.0f°/.", id(SOCStateOfcharge).state);          
          it.printf(60, 40, id(font_medium), "%.0f W", id(BatCurrentt).state);
          it.printf(0, 40, id(font_medium), "%.1fV", id(total_voltage).state);



            //мигаємо по стану конекта з ХА
          if (id(conekt_API).state) {id(HAapi_ani).next_frame(); it.image(0,0, id(HAapi_ani));}
            // рисуем палочки..
            int width = it.get_width();
            int height = it.get_height();
            // уровень сигнала..
            int rssi = 100;
            if (id(wifi_sig).has_state()) {
            rssi = id(wifi_sig).state;
            }
            int bars = 5;
            int bar_size = 3;
            int margin = 1;
            int x = width - (bar_size + margin) * bars - margin;
            int y = 0;
            int fill = 0;
            if (rssi > 50) {
            fill = 5;
            } else if (rssi > 40) {
            fill = 4;
            } else if (rssi > 30) {
            fill = 3;
            } else if (rssi > 20) {
            fill = 2;
            } else if (rssi > 10) {
            fill = 1;
            }
            for (int i = 0; i < bars; i++) {
            int itx = x + i * (bar_size + margin);
            int ity = y + (bars - i - 1) * bar_size;
            if (i < fill) {
              it.filled_rectangle(itx, ity, bar_size, bar_size + bar_size * i);
            } else {
              // it.rectangle(itx, ity, bar_size, bar_size + bar_size * i);
              it.line(itx, y + (bars * bar_size) - 1, itx + bar_size, y + (bars * bar_size) - 1);
            }
            }